MCU = atmega32u4
BOOTLOADER = caterina

SPLIT_KEYBOARD = yes
SWAP_HANDS_ENABLE = yes
LTO_ENABLE = yes

RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
